name: Android CI

on: workflow_dispatch

jobs:

  build-debug:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://gitee.com/RobinNotBad/BiliClient.git action_build_biliclient
    - name: ls
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
    - name: Upload APK(debug)
      uses: actions/upload-artifact@v3
      with:
          name: app-debug
          path: out/app-debug.*

  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://gitee.com/RobinNotBad/BiliClient.git action_build_biliclient
    - name: ls
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
    - name: sign app
    - run: |
          git clone https://github.com/hyj120309/Keystore.git
    - uses: r0adkll/sign-android-release@v1
      with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: MIIJwAIBAzCCCWoGCSqGSIb3DQEHAaCCCVsEgglXMIIJUzCCBaoGCSqGSIb3DQEHAaCCBZsEggWXMIIFkzCCBY8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFMW8ASf2/sCI2NwZI/I4Vw28btQiAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQbfR8s9xN7Fjmg0wX26Q6RASCBNCvc+eIDQ1zZ7QLpqHz9VF9d2+8s0aziG7WxVfJhtuAzpmy9hIkDeLiFJ6E5M4gJ9eSBg5gf6LS556fSrHHf6S5CWevOXdZW0IybdBx0jZ5O4XRrbonLsct6aUVxDcNoMZnXXaK0MMsRzolaWvs7vmlTHKsOguxy6WFQRYfZKXxiT6f+p4osqMuFo21ogdvO1M2kEh7Rsg9TvA6ft1l7vjcwZCRcAWmSNHTEbFmBr1lgvn2zY0J2Y/VYQXETsLlq1xvdzKEB76+pDVnhd7vgMg5VNEoRKfa7A0eBvwmMspJUgk6zolpa51dnmcm0QPeFS+NOqu8cwi22UVXNuZ339v3cjL+zLYFltSSKvF3ypbMmSH3gGtt4cLP4IwHhHI0AuexuMiog0gicCoW4HFcxqtJcfbrEQ3YrxTI/KIGOBTW63Awbrj851QG4TRgisPuBkZyCP9yVxCiYuU5QtanqBbvC3G84CX8bIhSzqsL3MPU4VDFIZMnSKy0MyzLWR0BFlxWgw3ZnN/yH2aVvxJhoZb6A8SfDep4J/pkNSelP5v/dQUh9gKi4PapEUkJyyid9UmZTOaBGaWSar+lWH8ZGAoof27yQ09KaOJpS1FrfvkeSXDIhJlAGLPImhJHpFY9fdDHlQZcUwDlb1cKq4Q0SBaNtGPpML9pbGJSbx9KePYDR3x3/ma5Eglqmy+fLl2Va02LAqlq4h/MozJqddSuGTGEkWLJYGcG9ZDRcW9Vf2uri3R25CzepoVgZGlmMB2C6C1iPL+hh2lfZE49jSnow9zZkm7bepKZdUGcOfwf6sUhsGsfFylLCzpUrwmjwe/NcCqoth+9Ng9jYFC2z90ne/Cj2pSNSls+2UWpzFExJqvV+8uO+vmDnDC/WVfJB9rafgUg1OjdlyQSQER6nTsniu4UccubmA9Ct0PuY1Ljm7zbZjFjarkb32PH9iLAC63Y3beyGfIIt17Iaedh4edRfhgyswFybNHoOoSCrcqyh4uAQ1+uegc9uNzLwu3qp9Dqlsa3OGTM57uNuyUbD7jYrIoSIrzU7hIX7MtX/qSoeWXzkO4D9HsTGW4nNeB+FcB/WFmURNWcw/6MaD9MdABNgAXbKJXeAkCtlepsoiR38YTm9jyGOqCNXXhtfIuXhF65+I8zyaLzSezO1zqvPtht7b82YnXdZxy9n7ms3OdRfiJf2/l5EbYWSV8KWg1Bg75BymSVzikVPjG9KFzHQFAoq76FlRmVaD2Lra9rwBELQZlM1hFMFZBAcxgLttSyBha8CddY6QsuUCPQjy7kh80dPzzutP/MHP2pT1u0FzVfr2foi7yuxv1eebFLn6GVsGjYpa26m49bzP6lUVZ12eMgmstLYxBbbjU9tuYUnbE8qqITZgUGvKjzJEgR/SKUVNjt50ZXX+mMjHYmuP+hTfLDrfSo4KeKL/tqWWZP3o5utyfgJg75LEF8fl+1lkuy793xVhxkkf/7ND6kMg7gmclQso5R/2GaQEaUsdOD30y4NFPuWgQUZwGrjmtTVDgw5VJmOhLhRmvEQobrWR5x4TjHt6V6N9ZATmWX0CHv8bRjDo2wPEkr5udEHFuzPfJPgH6jsrDOaVE8wof2pr1eeIKF/A/XBgbBfZKqEVWhke4Ci0kPFTE8MBcGCSqGSIb3DQEJFDEKHggAawBlAHkAMDAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzA1NzIxOTU4NjMzMIIDoQYJKoZIhvcNAQcGoIIDkjCCA44CAQAwggOHBgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFCIQFZlG9TPVy157TKR+O3r2vrxfAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQnrwZ1v8nRNLalEWQiTYx2ICCAxDUgZqKxkqBuai04F/UqWA1ZfMi75sorWuO+rSC5mirjoyE2wE7Leb6omYyopR1x3WKEx8uM9cDyzsv89tHRx5zvPV9bCY7PHt/FtAhU1kroucRPA2bRb8H6KfZSvmFpTHjkRp0EDqUu56sPdaCdliuY1tH9IxFyciXrp3QB3y2sW7mh9hzHIlXXynAaApRgpGqB9V7lhjC7EnD8LLuT9UfMz19T8lhe57TxrX4EeA1GVm2L9cBjyNZrSlJQEh+HH6O7y4pShLusXk+WRFDVPKoeiNN6ZhOqW0yq3+HkE8JEU0jTSCMGk8kkfDmMjSThrUHnzlxVEHI6bA9T72QVxpmYUH1MRB3qsMBQ4psnYVFV07s1SE1+lGr3/PZ1QnzZ/C6wQMrPgza0aut+9JP0SS0lhVIsCllhUxyqoqy+yuEf8+W2ZjW2BH/ihSjTJ8x+GmY7gbkfhe04NBZoWb8M9uAWAaFWx7LCDpwoufeWlGzFc9T8HdvCBWMjwu4Usx2vh4BZCBrVelpKqWqxdIlYpLHNs+/PnV/XSpKucg/kzFcwdKBWRQ3rBkYDDRKHlQ7CjU4E20vGC60585iTxq3ObL3Upp9VIS5x6WV00PGP79Y6aa4fy2j7LpnULurJeMzYf/SexBnpzlyDR5meZ4aP/X3VKRlpTkCB/KyQX4jfeSLqyfP8znuOnA9VK0T6WoAJSB661qF5bJ82YDlmm816HQKDAd+Ruu/5Yv6sc6j6cg9TYG/iH1tLUJzxhrt0PKxitp6m+43us+4mpUK/f4FvOWUN1hg1DnlnnhvbYSxLH0XxbM7Oa3RErDRskiNL3q+huN0maO8YSismn2F8IgkjDwBi5nIKlKkmiTBI7h3ZqVoiIgpu6nUhJvkxxWyYrGQ9pgcnid62wH9EUQh462UXCsh3xX5J0X4THTUVWadQX0oYAw5ymYZlAuRDbx+BAhBZqq+vqQHC7MeksWlwIN7S3EvqAa58RT9+EvW3KGmV0EYww37YcaAcrJU1WKiY/LPt8amh20FGO8GpH4VjF+/dLecME0wMTANBglghkgBZQMEAgEFAAQglE7KCZNNpztcD4QsYVCL8IbqP9lX3M+8Yg5yR+TVQ6UEFOs6xIy8w5pSlp8UHR1UqsQ+4VraAgInEA==
          alias: key0
          keyStorePassword: 120309
          keyPassword: 120309
    - run: mv ${{steps.sign_app.outputs.signedReleaseFile}} out/app-release.apk
    - name: Upload APK(release)
      uses: actions/upload-artifact@v3
      with:
          name: app-debug
          path: out/app-release.*   

