name: Android CI

on: 
    workflow_dispatch:
    schedule:
    - cron: "0 8 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://gitee.com/RobinNotBad/BiliClient.git action_build_biliclient
    - name: Troubleshoot errors
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
