name: Android CI

on: workflow_dispatch

jobs:

  build-debug:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://gitee.com/RobinNotBad/BiliClient.git action_build_biliclient
    - name: ls
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk out/app-debug.apk
    - name: Upload APK(debug)
      uses: actions/upload-artifact@v3
      with:
          name: app-debug
          path: out/app-debug.*

  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_biliclient && git clone -b develop https://gitee.com/RobinNotBad/BiliClient.git action_build_biliclient
    - name: ls
      run: ls -l /home/runner/work/action_build_biliclient/action_build_biliclient
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
          mv app/build/outputs/apk/release/app-release.apk out/app-release.apk
    - name: Upload APK(release)
      uses: actions/upload-artifact@v3
      with:
          name: app-debug
          path: out/app-release.*   

