name: Android CI

on: workflow_dispatch


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: git clone -b develop https://gitee.com/RobinNotBad/BiliClient.git action_build_biliclient
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
