name: BiliTerm2

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'
    - cron: '59 23 * * *'

jobs:
  
  build-new:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_center && git clone https://github.com/Re-BiliTerminal/BiliTerminal2.git action_build_center
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
          mv app/build/outputs/apk/release/app-release-unsigned.apk out/app-release.apk
    - name: Upload APK(release)
      uses: actions/upload-artifact@v4
      with:
          name: app
          path: out/app-release.apk 
