name: Android CI

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'
    - cron: '59 23 * * *'

jobs:

  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        repository: RJMultiDev/ono
        path: target
        fetch-depth: 0
        submodules: recursive
    - name: Grant execute permission for gradlew
      run: chmod +x ./target/gradlew
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          cd target
          ./gradlew :app:assembleRelease
    - uses: ilharp/sign-android-release@v2
      name: Sign app APK
      id: sign_app
      with:
          releaseDir: target/app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNKEY}}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}
          buildToolsVersion: 36.0.0
    - uses: actions/upload-artifact@v4
      name: Upload signed APK
      with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedFile}}