name: RWB

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'
    - cron: '59 23 * * *'

jobs:
  
  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone BiliClient
      run: cd .. && sudo rm -rf action_build_center && git clone https://github.com/SpaceXC/Re-WearBili.git action_build_center
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: mkdir
      run: mkdir out
    - name: Clone bilibili-kotlin-sdk
      run: cd libs && git clone https://github.com/SpaceXC/Bilibili-Kotlin-SDK.git
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew :app:assembleRelease
    - name: Upload APK(release)
      uses: actions/upload-artifact@v4
      with:
          name: app
          path: app/build/outputs/apk/   
   
