name: Build

on:
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:

    # 将内容推送到目标仓库
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: Hydramboo/Browser  # 目标仓库地址
          token: ${{ secrets.GH }}
          persist-credentials: false
          #path: target # 克隆到另一路径
          fetch-depth: 0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle Global Caches
        uses: actions/cache@v4
        with:
          path: |
             build
             .gradle
          key: gradle-global-cache
          restore-keys: |
            gradle-global-cache

      - name: Build with Gradle (Release)
        run: ./gradlew :app:assembleRelease --daemon --parallel 


      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk
          retention-days: 7
