name: TBS

on: 
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 12 * * *'
    - cron: '59 23 * * *'

jobs:
  
  build-release:

    runs-on: ubuntu-latest

    steps:
    - name: Git clone
      run: cd .. && sudo rm -rf action_build_center && git clone https://github.com/RJMultiDev/X5Demo.git action_build_center
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: mkdir
      run: mkdir ./out
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
          ./gradlew :app:assembleRelease
    - uses: ilharp/sign-android-release@v2
      name: Sign app APK
      id: sign_app
      with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.SIGNKEY}}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.PASSWORD }}
          keyPassword: ${{ secrets.PASSWORD }}
          buildToolsVersion: 36.0.0
    - uses: actions/upload-artifact@v4
      name: Upload signed APK
      with:
          name: app-signed
          path: ${{steps.sign_app.outputs.signedFile}}